[workspace]
authors = ["softwareentrepreneer <softwareentrepreneer+pfund-plot@gmail.com>"]
channels = ["conda-forge"]
name = "pfund-plot"
platforms = ["osx-arm64", "linux-64"]
# updating this needs to also update the version in the ci.yml and templates/ci-workflow-template.yml files
requires-pixi = ">=0.63.2"  # command: pixi workspace requires-pixi set ">=0.63.2

[tasks]

[tasks.test-all]
depends-on = [
  { task = "test", environment = "py311" },
  { task = "test", environment = "py312" },
  { task = "test", environment = "py313" },
]

[dependencies]
python = ">=3.11.14"
uv = ">=0.10.2"
gh = ">=2.87.2"

[pypi-dependencies]
# TEMP
pfund-plot = { path = ".", editable = true }
pfeed = { path = "../pfeed", editable = true }
pfund = { path = "../pfund", editable = true }
pfund-kit = { path = "../pfund-kit", editable = true }
# pfeed = ">=0.0.5"
panel = ">=1.8.9"
hvplot = ">=0.12.2"
anywidget = ">=0.9.21"
ipywidgets-bokeh = ">=1.6.0"
pywebview = ">=6.1"
datashader = ">=0.18.2"

# TEMP
[pypi-options.dependency-overrides]
pfund = { path = "../pfund", editable = true }
pfeed = { path = "../pfeed", editable = true }
pfund-kit = { path = "../pfund-kit", editable = true }

[environments]
default = ["py311", "dev", "optional"]
py311 = ["py311", "test", "optional"]
py312 = ["py312", "test", "optional"]
py313 = ["py313", "test", "optional"]

[feature.optional.pypi-dependencies]
marimo = { version = ">=0.20.4", extras = ["recommended", "lsp"] }
jupyter-bokeh = ">=4.0.5"
notebook = ">=7.5.4"
papermill = ">=2.7.0"
voila = ">=0.5.11"
matplotlib = ">=3.10.8"
plotly = ">=6.6.0"
vegafusion = ">=2.0.3"
altair = ">=6.0.0"

[feature.dev.dependencies]
ta-lib = ">=0.6.4"

[feature.dev.pypi-dependencies]
pfund-plot = { path = ".", editable = true }
afterpython = ">=0.2.1"
basedpyright = ">=1.38.0"
watchfiles = ">=1.1.1"  # "panel serve myfile.py --dev" requires watchfiles installed to autoreload
selenium = ">=4.39.0"  # saving bokeh images requires selenium
bokeh-sampledata = ">=2025.0"
hvsampledata = ">=0.1.4"
dayplot = ">=0.5.1"

[feature.test.pypi-dependencies]
pytest = ">=9.0.2"
pytest-cov = ">=7.0.0"
pytest-mock = ">=3.15.1"
pytest-xdist = ">=3.8.0"
[feature.test.tasks]
test = "pytest -v -n auto"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"
